# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flightline.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='flightline.proto',
  package='flightline',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x66lightline.proto\x12\nflightline\"\x99\x01\n\x08Scanline\x12*\n\x06points\x18\x01 \x03(\x0b\x32\x1a.flightline.Scanline.Point\x12\x0b\n\x03idx\x18\x02 \x01(\x05\x1aT\n\x05Point\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\x12\t\n\x01z\x18\x03 \x02(\x01\x12\t\n\x01i\x18\x04 \x02(\x05\x12\t\n\x01t\x18\x05 \x02(\x01\x12\t\n\x01\x65\x18\x06 \x02(\x08\x12\t\n\x01\x61\x18\x07 \x02(\x11\"5\n\nFlightline\x12\'\n\tscanlines\x18\x01 \x03(\x0b\x32\x14.flightline.Scanline')
)




_SCANLINE_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='flightline.Scanline.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='flightline.Scanline.Point.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='flightline.Scanline.Point.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='flightline.Scanline.Point.z', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='i', full_name='flightline.Scanline.Point.i', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t', full_name='flightline.Scanline.Point.t', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='e', full_name='flightline.Scanline.Point.e', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='a', full_name='flightline.Scanline.Point.a', index=6,
      number=7, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=186,
)

_SCANLINE = _descriptor.Descriptor(
  name='Scanline',
  full_name='flightline.Scanline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='flightline.Scanline.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='idx', full_name='flightline.Scanline.idx', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SCANLINE_POINT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=186,
)


_FLIGHTLINE = _descriptor.Descriptor(
  name='Flightline',
  full_name='flightline.Flightline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scanlines', full_name='flightline.Flightline.scanlines', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=241,
)

_SCANLINE_POINT.containing_type = _SCANLINE
_SCANLINE.fields_by_name['points'].message_type = _SCANLINE_POINT
_FLIGHTLINE.fields_by_name['scanlines'].message_type = _SCANLINE
DESCRIPTOR.message_types_by_name['Scanline'] = _SCANLINE
DESCRIPTOR.message_types_by_name['Flightline'] = _FLIGHTLINE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Scanline = _reflection.GeneratedProtocolMessageType('Scanline', (_message.Message,), dict(

  Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
    DESCRIPTOR = _SCANLINE_POINT,
    __module__ = 'flightline_pb2'
    # @@protoc_insertion_point(class_scope:flightline.Scanline.Point)
    ))
  ,
  DESCRIPTOR = _SCANLINE,
  __module__ = 'flightline_pb2'
  # @@protoc_insertion_point(class_scope:flightline.Scanline)
  ))
_sym_db.RegisterMessage(Scanline)
_sym_db.RegisterMessage(Scanline.Point)

Flightline = _reflection.GeneratedProtocolMessageType('Flightline', (_message.Message,), dict(
  DESCRIPTOR = _FLIGHTLINE,
  __module__ = 'flightline_pb2'
  # @@protoc_insertion_point(class_scope:flightline.Flightline)
  ))
_sym_db.RegisterMessage(Flightline)


# @@protoc_insertion_point(module_scope)
